### PR TITLE
Improving app translation process v2

### PR DESCRIPTION
**Pull request by edmoss345**

### CODE REVIEW

**Comment by edmoss345** [comment]
Following on from comments in #29 have made the changes in this PR. Have made a new PR as I know @esmeetewinkel was using the existing script in her workflow so didn't want to disrupt.

@esmeetewinkel could you review this from a functional perspective, hopefully the README makes sense.

@istride could you have a look from a technical perspective to see if this is ok. Have now moved everything over to run off python

**Review by esmeetewinkel — APPROVED** [review]
This is working well, I've tested both scripts. 

I came across one point of improvement that I hadn't mentioned to you before: 
For some reason certain strings in the `.json` get split into multiple substrings (some of which are empty) in the `.pot` file. These later get merged into fewer strings by Crowdin, and so this twice causes a whole lot of changes that are not easy to check. I'm not exactly sure what's the "rule" that Crowdin is following for its splitting into substrings - but for sure every string of the form `msgid "" "Some text"` gets replaced by `msgid "Some text`. If you have some future improvement to suggest here that would be great. 

image

image

**Review by esmeetewinkel — COMMENTED** [review]
I noticed that the merge post translation script does not yet look exactly in the folders I need - it is for sure also taking some parent text folders when I'm running it on the parent app config. I can have a closer look later. The file names in the Crowdin-linked repo are actually not exactly the same as the names we've given to the split groups, so that might mess things up. 

image

**Comment by edmoss345** [comment]
@esmeetewinkel thanks for comment above. Have made a change to the script so you can just provide a list of files for the 'merge' script to look at, as you previously suggested. This should hopefully work better and mean there is no problem if the folders we get back from the translators have different names.

**Pull request merged**
